# Generated by Django 6.1.1 on 2026-09-11 14:44

import django.db.models.deletion
import django.utils.timezone
import shopapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Insurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название страховки"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("auto", "Автострахование"),
                            ("health", "Медицина"),
                            ("property", "Имущество"),
                        ],
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание условий")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Цена в год (руб.)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Доступно для покупки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Страховой продукт",
                "verbose_name_plural": "Страховые продукты",
            },
        ),
        migrations.CreateModel(
            name="UserPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Номер полиса"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Дата начала"
                    ),
                ),
                ("end_date", models.DateField(verbose_name="Дата окончания")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активен"),
                            ("expired", "Истёк"),
                            ("canceled", "Аннулирован"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("user_auto", models.TextField(blank=True, null=True)),
                (
                    "prewiew",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=shopapp.models.auto_prewiew_directory_path,
                    ),
                ),
                (
                    "insurance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shopapp.insurance",
                        verbose_name="Страховой продукт",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Купленный полис",
                "verbose_name_plural": "Купленные полисы",
            },
        ),
        migrations.CreateModel(
            name="AutoImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=shopapp.models.auto_images_directory_path
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=200)),
                (
                    "auto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shopapp.userpolicy",
                    ),
                ),
            ],
        ),
    ]
